name: Audit dependencies

on:
  push:
    branches:
      - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validate-dependencies:
    name: Validate production dependencies
    runs-on: ubuntu-latest
    continue-on-error: false
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: Prepare Environment
        run: |
          yarn install
        env:
          CI: true
      - name: Validate dependencies
        run: |
          yarn validate:dependencies
        env:
          CI: true
  validate-all-dependencies:
    name: Validate all dependencies
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: Prepare Environment
        run: |
          yarn install
        env:
          CI: true
      - name: Validate dependencies
        run: |
          yarn validate:dev-dependencies
        env:
          CI: true
