name: Node CI - Lint and Test

on:
  push:
    branches:
      - '**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  pull_request:

jobs:
  lint:
    name: Lint and Type check
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Prepare Environment
        run: |
          corepack enable
          yarn install
      - name: Type check
        run: yarn build
        env:
          CI: true
      - name: Lint
        run: |
          yarn lint
        env:
          CI: true

  test:
    name: Test on node ${{ matrix.node_version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node_version: [22.x, 24.x]

    timeout-minutes: 5
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node_version }}
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Prepare Environment
        run: |
          corepack enable
          yarn install
          yarn build
        env:
          CI: true
      - name: Run unit tests
        run: |
          yarn test -- --maxWorkers=2 --forceExit --coverage
        env:
          CI: true
      - name: Send coverage
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  validate-dependencies:
    name: Validate production dependencies
    runs-on: ubuntu-latest
    continue-on-error: false
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Use Node.js 22
        uses: actions/setup-node@v6
        with:
          node-version: 22
      - name: Prepare Environment
        run: |
          corepack enable
          yarn install
        env:
          CI: true
      - name: Validate dependencies
        run: |
          yarn validate:dependencies
        env:
          CI: true
